### PR TITLE
Enabled to set a file from the preview panel.

### PR DESCRIPTION
**Pull request by hiroyuki-komatsu**
* Also enabled to show the current input source in the preview.
* Added ui/events.py
  + EVT_INPUT_FILE_ADDED: Event a new video file is added.
  + EVT_INPUT_INITIALIZED: Event input source is updated.
* Moved the text box for video file from Options to Preview.
  + Stopped to store the value of the text box to the config file.

### CODE REVIEW

**Comment by hiroyuki-komatsu** [comment]
Screenshots:

**Comment by hasegaw** [comment]
Thanks for the work. I'd like to do some tests on Windows environment before merging.

**Comment by frozenpandaman** [comment]
Cool! :)

**Comment by hiroyuki-komatsu** [comment]
Fixed the issue on Windows discussed in the team Slack.

66fa538 is the change.

**Pull request merged**
