### PR TITLE
Use `context['game']['end_time']` as timestamps

### PR DESCRIPTION
**Pull request by eagletmt**
For non-realtime input (i.e. CVFile), using
`context['game']['end_time']` is better, I think, than `datetime.now()`.

### CODE REVIEW

**Comment by hasegaw** [comment]
Thanks for the proposal. I believe context['game']['end_time'] can be None in some cases.

**Comment by hasegaw** [comment]
dhcp44-80:http hasegaw$ python3
Python 3.4.3 (default, Jul 13 2015, 12:18:23)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> datetime.fromtimestamp(0)
datetime.datetime(1970, 1, 1, 9, 0)
>>> datetime.fromtimestamp(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: an integer is required (got type NoneType)

**Comment by eagletmt** [comment]
Added fallback to `datetime.now()`.

**Comment by hasegaw** [comment]
LGTM. Thanks!

**Pull request merged**
