### PR TITLE
Return results about kill_combo and kill_streak to stat.ink

### PR DESCRIPTION
**Pull request by southws**
- Return result about chained_kill_combo event for 'events'
- Return result about streak parameter into on_game_killed event for 'events'.
- Return results about max_kill_combo and max_kill_streak.
- This pull request is based on follow request:
   -  https://github.com/hasegaw/IkaLog/pull/269

### CODE REVIEW

**Comment by fetus-hina** [comment]
stat.ink will not implement to use these data.

* `max_kill_*`:
  - These data will not be displayed and/or used to stats. (stat.ink may implement it, but it is unlikely to do it in the near future.)
* `events`' `streak`:
  - stat.ink will not use this payload's data. It will calculate at render-time because it is view-related data.  It is not a model data.
    https://twitter.com/fetus_hina/status/733927622254567424 https://twitter.com/fetus_hina/status/733927731570712576

**Comment by hasegaw** [comment]
@fetus-hina's comment makes sense to me. Since this change affects only stat.ink submission, no strong reason to merge. I'll keep this open for a while, just in case.

**Comment by southws** [comment]
I didn't read these tweet. I respect @fetus-hina's opinion, then I should remove L356-361 and L770-773 changes at least.
It's suggestion to show result (not real-time) details about the situation advantage of the game and inkling's real skill between respawn and dead, than total kill/death rate. The combo and the streak are one side of indicator I think.

**Comment by hasegaw** [comment]
For ``max_kill_*`` keys, I agree those are interesting metrics to review the games, especially for ranked battles.

I'm positive to merge if stat.ink (eventually) supports them and the keys ``max_kill_combo`` ``max_kill_streak`` are considered reasonable.

**Comment by fetus-hina** [comment]
- `max_kill_combo` : I'll implement this metric in `v1.60.0` or something in the near future.
- `max_kill_streak` : Also this.
- `events.chained_kill_combo` : I think no need to add new data to display combo/streak counter. I think stat.ink can and should detects from current format. Because:
  - It's a view-related data.
  - stat.ink will not handle well the event by structural reason.
  - Once stat.ink supports this detection, it can be applied to existing games.

**Comment by hasegaw** [comment]
@fetus-hina: Thanks.
@southws: Now we are ready to move forward. Please submit the max_kill_* changes, as a new pull request.

**Pull request closed without merging**
